apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::195938421275:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-190R3CQ49SMJC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::195938421275:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-22T10:18:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "67954"
  uid: 53baf571-f135-4a6c-9907-dc2df15f7a2c

